version: '2'

services:
  mysql:
    hostname: ${MYSQL_HOST}
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    labels:
      project: ${PROJECT_NAME}
      container: ${COMPOSE_PROJECT_NAME}_mysql
    volumes:
      - ${PACKAGE_DOCKER_FOLDER}/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf
      - ${PROJECT_DOCKER_FOLDER}/mysql/storage:/var/lib/mysql
      - ${PROJECT_DOCKER_FOLDER}/mysql/logs:/var/log/mysql
    networks:
      common:
        aliases:
          - ${MYSQL_HOST}