FROM matthewpatell/universal-docker-server:3.8

# TODO: write script which will generate group of dockerfiles with same version

RUN apt-get install -y \
    php7.1-dev \
    php7.1-phpdbg \
    php-codesniffer
