version: '2'

services:
  nginx:
    ports:
      - ${SERVER_HTTP_PORT}:80
      - ${SERVER_SSL_PORT}:443

  server:
    ports:
      - ${SSH_PORT}:22

  mysql:
    ports:
      - ${MYSQL_PORT}:3306

  redis:
    ports:
      - ${REDIS_PORT}:6379