version: '2'

services:
  server_test:
    extends:
      file: docker-compose.php-fpm.yml
      service: server
    depends_on:
      - server
      - nginx
    container_name: ${COMPOSE_PROJECT_NAME}_server_test
    labels:
      tests: yes
    networks:
      common:
        aliases:
          - server_test