version: '2'

services:
  nginx:
    env_file: .env
    depends_on:
      - redis

  mysql:
    env_file: .env
    hostname: ${MYSQL_HOST}
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${PROJECT_ROOT}/docker/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf
      - ${PROJECT_ROOT}/docker/mysql/storage:/var/lib/mysql
      - ${PROJECT_ROOT}/docker/mysql/logs:/var/log/mysql
    networks:
      main_x:
        aliases:
          - ${MYSQL_HOST}

  redis:
    env_file: .env

  server:
    env_file: .env
    depends_on:
      - mysql
      - redis
