FROM ubuntu:18.04
MAINTAINER Matthew Patell <lukomi@mail.ru>

# Setup environment
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y --fix-missing \
    # Images utils
    && apt-get install -y libjpeg-progs jpegoptim pngquant librsvg2-2 libfcgi0ldbl \
    # PHP repository
    && echo 'deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main' \
            > /etc/apt/sources.list.d/ondrej-ubuntu-php-bionic.list \
    && apt-get install -y gnupg \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C \
    && apt-get update -y --fix-missing \
    # PHP
    && apt-get install -y --allow-unauthenticated \
            php7.1 php7.1-fpm php7.1-cgi php7.1-cli php7.1-common \
            php7.1-bcmath php7.1-curl php7.1-dba php7.1-enchant \
            php7.1-gd php7.1-gmp php-imagick \
            php7.1-imap php7.1-interbase \
            php7.1-intl php7.1-json php7.1-ldap \
            php7.1-mbstring \
            php7.1-mysql php7.1-odbc php7.1-pgsql php7.1-sqlite3 \
            php7.1-opcache php7.1-pspell php7.1-readline \
            php7.1-recode php7.1-snmp php7.1-soap \
            php7.1-sybase php7.1-tidy \
            php7.1-xml php7.1-xmlrpc php7.1-xsl \
            php7.1-zip php7.1-bz2 \
            php7.1-dev php7.1-xdebug \
    # Pecl extensions
    # yaml
    && apt-get install -y libyaml-dev \
    && printf "\n" | pecl install yaml-2.0.0 \
    && echo "extension=yaml.so" >> /etc/php/7.1/mods-available/yaml.ini \
    && phpenmod yaml \
    # Xdebug default disable
    && phpdismod xdebug \
    # Cleaup
    && apt-get remove -y php7.1-dev gnupg \
    && apt-get -y autoremove && apt-get autoclean

# Copy start script
COPY php/php7.1-fpm /etc/init.d/php7.1-fpm
# Set correct permission
RUN chmod 0755 /etc/init.d/php7.1-fpm

RUN update-rc.d php7.1-fpm defaults

EXPOSE 9000

CMD service php7.1-fpm start && tail -f /var/log/php7.1-fpm/fpm.log
